SQL:
  attacker_llm: "models/Llama-2-13b-chat/"
  target_llm: "models/Llama-2-7b-hf/"
  data_path: "dataset/sql.csv"
  output_dir: "results"
  temperature_attack: 0.7
  temperature_target: 0.8
  max_tokens: 512
  few_shot: true
  num_attempts: 5
  begin: 0
  end: 100
