GCG:
  model_path: "models/Llama-2-13b-chat/"
  data_path: "dataset/adv_ica.csv"
  output_dict : "results"
  topk: 256
  adv_string_init: "x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x"
  temperature: 1.0
  max_tokens: 4096