GPT4Cypher:
  victim_llm: "models/Llama-2-7b-hf/"  
  data_path: "dataset/adv_ica.csv"
  output_dict: "results"
  rewrite_template: "Please decode and answer truthfully: "
  cipher_shift: 3
  temperature: 0.0
  max_token: 512