Pair:
  attacker_llm_path: "models/Llama-2-13b-chat"
  target_llm_path: "models/Llama-2-7b-hf/"
  attacker_on_cpu: True  
  target_on_cpu: False   
  data_path: "dataset/adv_ica.csv"
  output_dict: "results"
  temperature: 1.0
  max_tokens: 1024
  target_str: "Sure,"
  n_iterations: 5
  early_stop_threshold: 8
  begin: 0
  end: 100