RandomSearch:
  victim_llm: "/storage/brno2/home/xkaska01/master/my_implementation/models/Llama-2-7b-hf/"
  data_path: "/storage/brno2/home/xkaska01/master/my_implementation/dataset/cysecbench_adv.csv"
  output_dict: "/storage/brno2/home/xkaska01/master/my_implementation/results"
  temperature: 1.0
  max_token: 4096
  target_str: "Sure,"
  max_iterations: 3
  max_restarts: 3
  max_n_to_change: 8
  begin: 0
  end: 13282
