TAP:
  data_path: dataset/adv_ica.csv
  output_dir: results        
  victim_llm: models/Llama-2-7b-hf
  attacker_llm: models/Llama-2-7b-hf
  temperature: 0.8    
  max_token: 1024     
  width: 8            
  branching: 8        
  depth: 8            
  target_str: "Sure." 
  begin: 0            
  end: 100            
