TAP:
  data_path: dataset/adv_ica.csv
  output_dir: results        
  victim_llm: models/Llama-2-7b-hf
  attacker_llm: models/Llama-2-7b-hf
  temperature: 0.8    
  max_token: 1024     
  width: 4            
  branching: 4        
  depth: 4            
  target_str: "Sure." 
  begin: 0            
  end: 13282            
