ArtPrompt:
  max_token:       512
  mask_llm_path:   "models/Llama-2-7b-hf"
  mask_temperature: 0.7
  mask_max_token:   256
  ascii_font_file: "/storage/brno2/home/xkaska01/master/my_implementation/attacks/_21_Art_Prompt/art.json"
  cot: false