# @file configCypher.yaml
# @brief Configuration file for Cypher query generation
#
# @author Bc. Petr Kaška
# @date 30.1.2026
#

Cypher:
  # @brief Controls the randomness of the generated output.
  # @details Higher values produce more creative but less deterministic. 
  # @range 0.0 – 1.0
  temperature: 0.8

  # @brief Maximum number of tokens in the generated output. 
  # @details Limits the length of the generated Cypher. 
  max_token: 512

  # @brief Cypher generation mode
  # @details Defines formatting and syntactic constraints applied during Cypher attack creation.
  cypher_mode: "WS"

  # @brief Enables or disables few-shot learning
  # @details When set to false, the model generates Cypher queries without using example attack prompts.
  few_shot: false

  # @brief Start index of the processed input
  # @details Specifies the index from which the input text processing begins.
  begin: 0

  # @brief End index of the processed input
  # @details Specifies the index at which the input text processing ends.
  end: 13282