run_defense: false
victim_llm: "/storage/brno2/home/xkaska01/master/my_implementation/models/Llama-2-7b-hf/"
dataset_path: "/storage/brno2/home/xkaska01/master/my_implementation/dataset/dataset_40.csv"
results_dir: "/storage/brno2/home/xkaska01/master/my_implementation/results/DATASET_C_gemma3:27b/"
use_ollama: true # true = ollama, false = vllm 
ollama_model:  "gemma3:27b"
defense:

evaluator: